SENSEI_ENV = {
  BUILD_STAGE: "alpha",
  FIREBASE_DB: "PRODUCTION",
  SERVER_HOST: "/api",
  RANK_PREDICT_HOST: "https://ai-sensei.com/rank-predict",
  HUMANLIKE_HOST: "https://ai-sensei.com/predict-humanlike",
  ENABLE_HUMANLIKE_BOTS: "true",
  ENABLE_HUMANLIKE_BOTS_JP: "true",
  ENABLE_HUMANLIKE_ANALYSIS: "true",
  USE_NEW_SCHEDULER: "true",
  WS_SCHEDULER_URL: "wss://ai-sensei.com/ws",
  NEW_SCHEDULER_URL: "wss://ai-sensei.com/ws2",
  ENABLE_FAST_LEVEL_UP: "true",
  ENABLE_BUNDESLIGA_STATS: "true",
  READ_FROM_FIRESTORE_DURING_MIGRATION: "true",
  ENABLE_PANDANET_GAME_IMPORT: "true",
};
