(function(){
'use strict';
var $cljs$core$update_keys$$ = function($m$jscomp$72$$, $f$jscomp$337$$) {
  var $ret$jscomp$60$$ = $APP.$cljs$core$persistent_BANG_$$($APP.$cljs$core$reduce_kv$$(function($acc$jscomp$9$$, $k$jscomp$228$$, $v$jscomp$81$$) {
    return $APP.$cljs$core$assoc_BANG_$$.$cljs$core$IFn$_invoke$arity$3$($acc$jscomp$9$$, $f$jscomp$337$$.$cljs$core$IFn$_invoke$arity$1$ ? $f$jscomp$337$$.$cljs$core$IFn$_invoke$arity$1$($k$jscomp$228$$) : $f$jscomp$337$$.call(null, $k$jscomp$228$$), $v$jscomp$81$$);
  }, $APP.$cljs$core$_as_transient$$($APP.$cljs$core$PersistentArrayMap$EMPTY$$), $m$jscomp$72$$));
  return $APP.$cljs$core$with_meta$$($ret$jscomp$60$$, $APP.$cljs$core$meta$$($m$jscomp$72$$));
}, $sensei$common$board$symmetries$apply_board$$ = function($board$jscomp$44$$) {
  function $update_history$$($history$jscomp$3$$) {
    return $APP.$cljs$core$mapv$cljs$0core$0IFn$0_invoke$0arity$02$$(function($color$jscomp$82_p__82708$$) {
      var $point$jscomp$19$$ = $APP.$cljs$core$nth$cljs$0core$0IFn$0_invoke$0arity$03$$($color$jscomp$82_p__82708$$, 0, null);
      $color$jscomp$82_p__82708$$ = $APP.$cljs$core$nth$cljs$0core$0IFn$0_invoke$0arity$03$$($color$jscomp$82_p__82708$$, 1, null);
      return new $APP.$cljs$core$PersistentVector$$(null, 2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$update_move$$($point$jscomp$19$$), $color$jscomp$82_p__82708$$], null);
    }, $history$jscomp$3$$);
  }
  function $update_move$$($p1__82694_SHARP_$$) {
    return $APP.$sensei$common$board$symmetries$apply_move$$($p1__82694_SHARP_$$, $board_size$jscomp$66$$, 3);
  }
  var $map__82695__$1$$ = $APP.$cljs$core$__destructure_map$$($board$jscomp$44$$), $board_size$jscomp$66$$ = $APP.$cljs$core$get$cljs$0core$0IFn$0_invoke$0arity$02$$($map__82695__$1$$, $APP.$cljs$cst$746$board_size$$);
  return $APP.$cljs$core$update$$.$cljs$core$IFn$_invoke$arity$3$($APP.$cljs$core$update$$.$cljs$core$IFn$_invoke$arity$3$($APP.$cljs$core$update$$.$cljs$core$IFn$_invoke$arity$3$($APP.$cljs$core$update$$.$cljs$core$IFn$_invoke$arity$3$($board$jscomp$44$$, $APP.$cljs$cst$2325$ko$$, function($ko$jscomp$3$$) {
    return $APP.$cljs$core$truth_$$($ko$jscomp$3$$) ? $update_move$$($ko$jscomp$3$$) : null;
  }), $APP.$cljs$cst$2318$stones$$, function($stones$jscomp$14$$) {
    return $cljs$core$update_keys$$($stones$jscomp$14$$, $update_move$$);
  }), $APP.$cljs$cst$2322$history$$, $update_history$$), $APP.$cljs$cst$2321$initial_stones$$, $update_history$$);
}, $sensei$frontend$play_ai$sidebar$undo_button$$ = function($game_uid$jscomp$144$$, $game_id$jscomp$422$$) {
  var $map__83958_map__83958__$1$$ = $APP.$cljs$core$deref$$($APP.$re_frame$core$subscribe$cljs$0core$0IFn$0_invoke$0arity$01$$(new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$3856$sensei_DOT_frontend_DOT_play_ai_DOT_db_SLASH_game_data$$, $game_uid$jscomp$144$$, $game_id$jscomp$422$$], null)));
  $map__83958_map__83958__$1$$ = $APP.$cljs$core$__destructure_map$$($map__83958_map__83958__$1$$);
  var $color$jscomp$106$$ = $APP.$cljs$core$get$cljs$0core$0IFn$0_invoke$0arity$02$$($map__83958_map__83958__$1$$, $APP.$cljs$cst$2311$color$$), $nodes$jscomp$167$$ = $APP.$cljs$core$get$cljs$0core$0IFn$0_invoke$0arity$02$$($map__83958_map__83958__$1$$, $APP.$cljs$cst$3190$nodes$$), $result$jscomp$151$$ = $APP.$cljs$core$deref$$($APP.$re_frame$core$subscribe$cljs$0core$0IFn$0_invoke$0arity$01$$(new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$3855$sensei_DOT_frontend_DOT_play_ai_DOT_db_SLASH_result$$, 
  $game_uid$jscomp$144$$, $game_id$jscomp$422$$], null)));
  return $APP.$cljs$core$truth_$$(function() {
    var $and__5023__auto__$jscomp$357$$ = $APP.$cljs$core$not$$($result$jscomp$151$$);
    return $and__5023__auto__$jscomp$357$$ ? $APP.$cljs$core$some$$(function($node$jscomp$232$$) {
      var $and__5023__auto____$1$jscomp$111$$ = $APP.$cljs$cst$850$move$$.$cljs$core$IFn$_invoke$arity$1$($node$jscomp$232$$);
      return $APP.$cljs$core$truth_$$($and__5023__auto____$1$jscomp$111$$) ? $APP.$cljs$core$_EQ_$$.$cljs$core$IFn$_invoke$arity$2$($APP.$cljs$cst$2311$color$$.$cljs$core$IFn$_invoke$arity$1$($node$jscomp$232$$), $color$jscomp$106$$) : $and__5023__auto____$1$jscomp$111$$;
    }, $APP.$sensei$common$model$variations$main_variation$$($nodes$jscomp$167$$)) : $and__5023__auto__$jscomp$357$$;
  }()) ? new $APP.$cljs$core$PersistentVector$$(null, 2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$sensei$frontend$widget$dropdown$menu_item$$, new $APP.$cljs$core$PersistentArrayMap$$(null, 3, [$APP.$cljs$cst$2111$label$$, $APP.$cljs$cst$1368$undo_last_move$$, $APP.$cljs$cst$3513$icon$$, new $APP.$cljs$core$PersistentVector$$(null, 1, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$5263$i_DOT_fas_DOT_fa_reply$$], null), $APP.$cljs$cst$1713$on_click$$, function() {
    return $APP.$re_frame$router$dispatch$$(new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$5240$sensei_DOT_frontend_DOT_play_ai_DOT_db_SLASH_undo_last_move$$, $game_uid$jscomp$144$$, $game_id$jscomp$422$$], null));
  }], null)], null) : null;
}, $sensei$frontend$play_ai$sidebar$game_dropdown_menu$$ = function($game_uid$jscomp$146$$, $game_id$jscomp$424$$) {
  return new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$sensei$frontend$widget$dropdown$menu$$, new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$sensei$frontend$play_ai$sidebar$undo_button$$, $game_uid$jscomp$146$$, $game_id$jscomp$424$$], null), new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$sensei$frontend$play_ai$sidebar$delete_button$$, 
  $game_uid$jscomp$146$$, $game_id$jscomp$424$$], null)], null);
}, $sensei$frontend$play_ai$sidebar$game_row$$ = function($game_uid$jscomp$148$$, $game_id$jscomp$426$$) {
  var $uid$jscomp$148$$ = $APP.$cljs$core$deref$$($APP.$re_frame$core$subscribe$cljs$0core$0IFn$0_invoke$0arity$01$$(new $APP.$cljs$core$PersistentVector$$(null, 1, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$2265$current_uid$$], null))), $game$jscomp$32$$ = $APP.$cljs$core$deref$$($APP.$re_frame$core$subscribe$cljs$0core$0IFn$0_invoke$0arity$01$$(new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$3856$sensei_DOT_frontend_DOT_play_ai_DOT_db_SLASH_game_data$$, 
  $game_uid$jscomp$148$$, $game_id$jscomp$426$$], null))), $board$jscomp$66_captures$jscomp$4$$ = $APP.$cljs$core$deref$$($APP.$re_frame$core$subscribe$cljs$0core$0IFn$0_invoke$0arity$01$$(new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$5222$sensei_DOT_frontend_DOT_play_ai_DOT_db_SLASH_board$$, $game_uid$jscomp$148$$, $game_id$jscomp$426$$], null)));
  $board$jscomp$66_captures$jscomp$4$$ = $APP.$cljs$cst$1058$captures$$.$cljs$core$IFn$_invoke$arity$1$($board$jscomp$66_captures$jscomp$4$$);
  var $sgf_info$jscomp$18$$ = $APP.$sensei$frontend$play_ai$db$calc_sgf_info$$($APP.$cljs$core$assoc$$.$cljs$core$IFn$_invoke$arity$3$($game$jscomp$32$$, $APP.$cljs$cst$3084$game_uid$$, $game_uid$jscomp$148$$));
  return new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$sensei$frontend$board$game_row$content$$, new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$3297$div_DOT_d_flex_DOT_align_items_center$$, new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$sensei$frontend$widget$players$player_names$$, $sgf_info$jscomp$18$$, new $APP.$cljs$core$PersistentArrayMap$$(null, 
  1, [$APP.$cljs$cst$4157$single_row_QMARK_$$, !1], null)], null), new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$5267$span_DOT_font_large_DOT_ps_2_DOT_mx_auto$$, new $APP.$cljs$core$PersistentVector$$(null, 2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$sensei$frontend$play_ai$sidebar$captures_component$$, $APP.$cljs$cst$627$white$$.$cljs$core$IFn$_invoke$arity$2$($board$jscomp$66_captures$jscomp$4$$, 0)], null), new $APP.$cljs$core$PersistentVector$$(null, 
  2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$sensei$frontend$play_ai$sidebar$captures_component$$, $APP.$cljs$cst$1616$black$$.$cljs$core$IFn$_invoke$arity$2$($board$jscomp$66_captures$jscomp$4$$, 0)], null)], null)], null), $APP.$cljs$core$_EQ_$$.$cljs$core$IFn$_invoke$arity$2$($uid$jscomp$148$$, $game_uid$jscomp$148$$) && $APP.$cljs$core$not$$($APP.$cljs$cst$5210$ranked_QMARK_$$.$cljs$core$IFn$_invoke$arity$1$($game$jscomp$32$$)) ? function() {
    return $APP.$re_frame$core$dispatch$$(new $APP.$cljs$core$PersistentVector$$(null, 2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$4253$sensei_DOT_frontend_DOT_widget_DOT_dropdown_SLASH_show$$, new $APP.$cljs$core$PersistentArrayMap$$(null, 3, [$APP.$cljs$cst$3376$anchor$$, $APP.$cljs$cst$4326$sidebar_menu_button$$, $APP.$cljs$cst$4235$widget$$, new $APP.$cljs$core$Var$$(function() {
      return $sensei$frontend$play_ai$sidebar$game_dropdown_menu$$;
    }, $APP.$cljs$cst$5268$sensei_DOT_frontend_DOT_play_ai_DOT_sidebar_SLASH_game_dropdown_menu$$, $APP.$cljs$core$PersistentHashMap$fromArrays$$([$APP.$cljs$cst$176$ns$$, $APP.$cljs$cst$180$name$$, $APP.$cljs$cst$1656$file$$, $APP.$cljs$cst$1666$end_column$$, $APP.$cljs$cst$1664$column$$, $APP.$cljs$cst$1657$line$$, $APP.$cljs$cst$1665$end_line$$, $APP.$cljs$cst$1945$arglists$$, $APP.$cljs$cst$1946$doc$$, $APP.$cljs$cst$171$test$$], [$APP.$cljs$cst$5265$sensei_DOT_frontend_DOT_play_ai_DOT_sidebar$$, 
    $APP.$cljs$cst$4409$game_dropdown_menu$$, "sensei/frontend/play_ai/sidebar.cljs", 25, 1, 58, 58, $APP.$cljs$core$list$$(new $APP.$cljs$core$PersistentVector$$(null, 4, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$4151$game_uid$$, $APP.$cljs$cst$4152$game_id$$, $APP.$cljs$cst$1785$_$$, $APP.$cljs$cst$1785$_$$], null)), null, $APP.$cljs$core$truth_$$($sensei$frontend$play_ai$sidebar$game_dropdown_menu$$) ? $sensei$frontend$play_ai$sidebar$game_dropdown_menu$$.$cljs$lang$test$ : 
    null])), $APP.$cljs$cst$2441$args$$, new $APP.$cljs$core$PersistentVector$$(null, 2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$game_uid$jscomp$148$$, $game_id$jscomp$426$$], null)], null)], null));
  } : null], null);
}, $sensei$frontend$play_ai$sidebar$handicap_row$$ = function($handicap$jscomp$12$$) {
  return $handicap$jscomp$12$$ > 0 ? new $APP.$cljs$core$PersistentVector$$(null, 2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$5269$div_DOT_play_ai_handicap_row$$, new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$sensei$common$i18n$view$label$$, $APP.$cljs$cst$1404$n_handicap$$, new $APP.$cljs$core$PersistentArrayMap$$(null, 1, [$APP.$cljs$cst$1911$n$$, $handicap$jscomp$12$$], null)], null)], null) : null;
}, $sensei$frontend$play_ai$sidebar$ai_move_generator$$ = function($game_uid$jscomp$149_humanlike_QMARK__map__83982_quality$jscomp$11_strategy$jscomp$2$$, $game_id$jscomp$427_request$jscomp$43$$, $board$jscomp$67$$) {
  var $analyzing_QMARK_$$ = $APP.$cljs$core$deref$$($APP.$re_frame$core$subscribe$cljs$0core$0IFn$0_invoke$0arity$01$$(new $APP.$cljs$core$PersistentVector$$(null, 1, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$3966$sensei_DOT_frontend_DOT_live_DOT_ws_client_SLASH_live_client_analyzing_QMARK_$$], null))), $status$jscomp$25$$ = $APP.$cljs$core$deref$$($APP.$re_frame$core$subscribe$cljs$0core$0IFn$0_invoke$0arity$01$$(new $APP.$cljs$core$PersistentVector$$(null, 1, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, 
  [$APP.$cljs$cst$3964$sensei_DOT_frontend_DOT_live_DOT_ws_client_SLASH_live_client_status$$], null))), $error$jscomp$54$$ = $APP.$cljs$core$deref$$($APP.$re_frame$core$subscribe$cljs$0core$0IFn$0_invoke$0arity$01$$(new $APP.$cljs$core$PersistentVector$$(null, 1, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$3965$sensei_DOT_frontend_DOT_live_DOT_ws_client_SLASH_live_client_error$$], null))), $last_request$$ = $APP.$cljs$core$deref$$($APP.$re_frame$core$subscribe$cljs$0core$0IFn$0_invoke$0arity$01$$(new $APP.$cljs$core$PersistentVector$$(null, 
  1, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$3927$sensei_DOT_frontend_DOT_live_DOT_ws_client_SLASH_last_analysis_request$$], null))), $disconnected_QMARK_$jscomp$1$$ = $status$jscomp$25$$ == null || $APP.$cljs$core$_EQ_$$.$cljs$core$IFn$_invoke$arity$2$($status$jscomp$25$$, $APP.$cljs$cst$2762$disconnected$$), $current_node_id$jscomp$13$$ = $APP.$cljs$core$deref$$($APP.$re_frame$core$subscribe$cljs$0core$0IFn$0_invoke$0arity$01$$(new $APP.$cljs$core$PersistentVector$$(null, 
  3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$5226$sensei_DOT_frontend_DOT_play_ai_DOT_db_SLASH_current_node_id$$, $game_uid$jscomp$149_humanlike_QMARK__map__83982_quality$jscomp$11_strategy$jscomp$2$$, $game_id$jscomp$427_request$jscomp$43$$], null))), $game$jscomp$33$$ = $APP.$cljs$core$deref$$($APP.$re_frame$core$subscribe$cljs$0core$0IFn$0_invoke$0arity$01$$(new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$3856$sensei_DOT_frontend_DOT_play_ai_DOT_db_SLASH_game_data$$, 
  $game_uid$jscomp$149_humanlike_QMARK__map__83982_quality$jscomp$11_strategy$jscomp$2$$, $game_id$jscomp$427_request$jscomp$43$$], null))), $plan$jscomp$24$$ = function() {
    var $or__5025__auto__$jscomp$491$$ = $APP.$cljs$core$deref$$($APP.$re_frame$core$subscribe$cljs$0core$0IFn$0_invoke$0arity$01$$(new $APP.$cljs$core$PersistentVector$$(null, 1, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$1039$current_plan$$], null)));
    return $APP.$cljs$core$truth_$$($or__5025__auto__$jscomp$491$$) ? $or__5025__auto__$jscomp$491$$ : $APP.$cljs$cst$717$free$$;
  }();
  $game_uid$jscomp$149_humanlike_QMARK__map__83982_quality$jscomp$11_strategy$jscomp$2$$ = $APP.$cljs$cst$3189$bot_data$$.$cljs$core$IFn$_invoke$arity$1$($game$jscomp$33$$);
  var $map__83982__$1_map__83983_map__83983__$1_override_settings$jscomp$2_play_ai_strength$jscomp$1$$ = $APP.$cljs$core$__destructure_map$$($game_uid$jscomp$149_humanlike_QMARK__map__83982_quality$jscomp$11_strategy$jscomp$2$$);
  $game_uid$jscomp$149_humanlike_QMARK__map__83982_quality$jscomp$11_strategy$jscomp$2$$ = $APP.$cljs$core$get$cljs$0core$0IFn$0_invoke$0arity$02$$($map__83982__$1_map__83983_map__83983__$1_override_settings$jscomp$2_play_ai_strength$jscomp$1$$, $APP.$cljs$cst$5169$strategy$$);
  $map__83982__$1_map__83983_map__83983__$1_override_settings$jscomp$2_play_ai_strength$jscomp$1$$ = $APP.$cljs$core$get$cljs$0core$0IFn$0_invoke$0arity$02$$($map__83982__$1_map__83983_map__83983__$1_override_settings$jscomp$2_play_ai_strength$jscomp$1$$, $APP.$cljs$cst$3192$settings$$);
  $map__83982__$1_map__83983_map__83983__$1_override_settings$jscomp$2_play_ai_strength$jscomp$1$$ = $APP.$cljs$core$__destructure_map$$($map__83982__$1_map__83983_map__83983__$1_override_settings$jscomp$2_play_ai_strength$jscomp$1$$);
  $map__83982__$1_map__83983_map__83983__$1_override_settings$jscomp$2_play_ai_strength$jscomp$1$$ = $APP.$cljs$core$get$cljs$0core$0IFn$0_invoke$0arity$03$$($map__83982__$1_map__83983_map__83983__$1_override_settings$jscomp$2_play_ai_strength$jscomp$1$$, $APP.$cljs$cst$3193$play_ai_strength$$, 15);
  var $humanlike_bot$$ = ($game_uid$jscomp$149_humanlike_QMARK__map__83982_quality$jscomp$11_strategy$jscomp$2$$ = $APP.$cljs$core$_EQ_$$.$cljs$core$IFn$_invoke$arity$2$($game_uid$jscomp$149_humanlike_QMARK__map__83982_quality$jscomp$11_strategy$jscomp$2$$, $APP.$cljs$cst$5170$humanlike$$)) ? $APP.$sensei$common$katago$bots$get_humanlike_bot$$($map__83982__$1_map__83983_map__83983__$1_override_settings$jscomp$2_play_ai_strength$jscomp$1$$) : null;
  $map__83982__$1_map__83983_map__83983__$1_override_settings$jscomp$2_play_ai_strength$jscomp$1$$ = $game_uid$jscomp$149_humanlike_QMARK__map__83982_quality$jscomp$11_strategy$jscomp$2$$ ? $APP.$cljs$cst$3958$override_settings$$.$cljs$core$IFn$_invoke$arity$1$($humanlike_bot$$) : null;
  $game_uid$jscomp$149_humanlike_QMARK__map__83982_quality$jscomp$11_strategy$jscomp$2$$ = $game_uid$jscomp$149_humanlike_QMARK__map__83982_quality$jscomp$11_strategy$jscomp$2$$ ? $APP.$cljs$core$get_in$cljs$0core$0IFn$0_invoke$0arity$02$$($humanlike_bot$$, new $APP.$cljs$core$PersistentVector$$(null, 2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$5191$move_selection$$, $APP.$cljs$cst$3094$quality$$], null)) : function() {
    var $G__83998$jscomp$inline_4465_or__5025__auto__$jscomp$inline_4464_quality$jscomp$12$$ = $APP.$cljs$core$get_in$cljs$0core$0IFn$0_invoke$0arity$02$$($game$jscomp$33$$, new $APP.$cljs$core$PersistentVector$$(null, 2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$3189$bot_data$$, $APP.$cljs$cst$3094$quality$$], null));
    $APP.$cljs$core$truth_$$($G__83998$jscomp$inline_4465_or__5025__auto__$jscomp$inline_4464_quality$jscomp$12$$) || ($G__83998$jscomp$inline_4465_or__5025__auto__$jscomp$inline_4464_quality$jscomp$12$$ = $APP.$cljs$core$get_in$cljs$0core$0IFn$0_invoke$0arity$03$$($game$jscomp$33$$, new $APP.$cljs$core$PersistentVector$$(null, 2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$3189$bot_data$$, $APP.$cljs$cst$2871$playouts$$], null), 2), $G__83998$jscomp$inline_4465_or__5025__auto__$jscomp$inline_4464_quality$jscomp$12$$ = 
    $APP.$sensei$common$payment$regions$b20_playouts__GT_plan$$.$cljs$core$IFn$_invoke$arity$1$ ? $APP.$sensei$common$payment$regions$b20_playouts__GT_plan$$.$cljs$core$IFn$_invoke$arity$1$($G__83998$jscomp$inline_4465_or__5025__auto__$jscomp$inline_4464_quality$jscomp$12$$) : $APP.$sensei$common$payment$regions$b20_playouts__GT_plan$$.call(null, $G__83998$jscomp$inline_4465_or__5025__auto__$jscomp$inline_4464_quality$jscomp$12$$));
    return $APP.$cljs$core$truth_$$($APP.$sensei$common$payment$regions$plan_at_least_QMARK_$$($G__83998$jscomp$inline_4465_or__5025__auto__$jscomp$inline_4464_quality$jscomp$12$$, $plan$jscomp$24$$)) ? $G__83998$jscomp$inline_4465_or__5025__auto__$jscomp$inline_4464_quality$jscomp$12$$ : $plan$jscomp$24$$;
  }();
  $game_id$jscomp$427_request$jscomp$43$$ = new $APP.$cljs$core$PersistentArrayMap$$(null, 6, [$APP.$cljs$cst$2326$board$$, $board$jscomp$67$$, $APP.$cljs$cst$139$type$$, $APP.$cljs$cst$5270$play$$, $APP.$cljs$cst$3094$quality$$, $game_uid$jscomp$149_humanlike_QMARK__map__83982_quality$jscomp$11_strategy$jscomp$2$$, $APP.$cljs$cst$3958$override_settings$$, $map__83982__$1_map__83983_map__83983__$1_override_settings$jscomp$2_play_ai_strength$jscomp$1$$, $APP.$cljs$cst$3348$game_id$$, $game_id$jscomp$427_request$jscomp$43$$, 
  $APP.$cljs$cst$3956$node_id$$, $current_node_id$jscomp$13$$], null);
  $disconnected_QMARK_$jscomp$1$$ && $APP.$cljs$core$not$$($error$jscomp$54$$) && $APP.$re_frame$router$dispatch$$(new $APP.$cljs$core$PersistentVector$$(null, 1, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$3969$sensei_DOT_frontend_DOT_live_DOT_ws_client_SLASH_connect$$], null));
  return $APP.$cljs$core$not$$($analyzing_QMARK_$$) && $APP.$cljs$core$_EQ_$$.$cljs$core$IFn$_invoke$arity$2$($status$jscomp$25$$, $APP.$cljs$cst$2763$connected$$) && $APP.$cljs$core$not_EQ_$$.$cljs$core$IFn$_invoke$arity$2$($APP.$cljs$core$dissoc$$.$cljs$core$IFn$_invoke$arity$2$($last_request$$, $APP.$cljs$cst$3933$start_time$$), $game_id$jscomp$427_request$jscomp$43$$) ? $APP.$re_frame$router$dispatch$$(new $APP.$cljs$core$PersistentVector$$(null, 2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, 
  [$APP.$cljs$cst$3955$send_live_analysis$$, $game_id$jscomp$427_request$jscomp$43$$], null)) : null;
}, $sensei$frontend$play_ai$sidebar$old_humanlike_generator$$ = function($game_uid$jscomp$150$$, $game_id$jscomp$428$$, $board$jscomp$68_request_data$jscomp$12$$) {
  var $game$jscomp$34_state$jscomp$91$$ = $APP.$cljs$core$deref$$($APP.$re_frame$core$subscribe$cljs$0core$0IFn$0_invoke$0arity$01$$(new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$3856$sensei_DOT_frontend_DOT_play_ai_DOT_db_SLASH_game_data$$, $game_uid$jscomp$150$$, $game_id$jscomp$428$$], null)));
  $board$jscomp$68_request_data$jscomp$12$$ = $APP.$sensei$frontend$humanlike$logic$request_data$$($board$jscomp$68_request_data$jscomp$12$$, $game$jscomp$34_state$jscomp$91$$);
  $game$jscomp$34_state$jscomp$91$$ = $APP.$cljs$core$deref$$($APP.$re_frame$core$subscribe$cljs$0core$0IFn$0_invoke$0arity$01$$(new $APP.$cljs$core$PersistentVector$$(null, 1, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$5241$sensei_DOT_frontend_DOT_play_ai_DOT_db_SLASH_humanlike_state$$], null)));
  return $APP.$cljs$core$_EQ_$$.$cljs$core$IFn$_invoke$arity$2$($board$jscomp$68_request_data$jscomp$12$$, $APP.$cljs$cst$3210$request_data$$.$cljs$core$IFn$_invoke$arity$1$($game$jscomp$34_state$jscomp$91$$)) ? null : $APP.$re_frame$router$dispatch$$(new $APP.$cljs$core$PersistentVector$$(null, 4, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$5242$sensei_DOT_frontend_DOT_play_ai_DOT_db_SLASH_call_humanlike$$, $game_uid$jscomp$150$$, $game_id$jscomp$428$$, $board$jscomp$68_request_data$jscomp$12$$], 
  null));
}, $sensei$frontend$play_ai$sidebar$mirror_move_generator$$ = function($game_uid$jscomp$151$$, $game_id$jscomp$429$$, $JSCompiler_temp$jscomp$4950_map__84044__$1_next_board$jscomp$2_p__84042$$) {
  $JSCompiler_temp$jscomp$4950_map__84044__$1_next_board$jscomp$2_p__84042$$ = $APP.$cljs$core$__destructure_map$$($JSCompiler_temp$jscomp$4950_map__84044__$1_next_board$jscomp$2_p__84042$$);
  var $board_size$jscomp$88_mirror_move$$ = $APP.$cljs$core$get$cljs$0core$0IFn$0_invoke$0arity$02$$($JSCompiler_temp$jscomp$4950_map__84044__$1_next_board$jscomp$2_p__84042$$, $APP.$cljs$cst$746$board_size$$), $history__$1$jscomp$3_last_move$jscomp$3$$ = $APP.$cljs$core$get$cljs$0core$0IFn$0_invoke$0arity$02$$($JSCompiler_temp$jscomp$4950_map__84044__$1_next_board$jscomp$2_p__84042$$, $APP.$cljs$cst$2322$history$$);
  $history__$1$jscomp$3_last_move$jscomp$3$$ = $APP.$cljs$core$first$$($APP.$cljs$core$peek$$($history__$1$jscomp$3_last_move$jscomp$3$$));
  $board_size$jscomp$88_mirror_move$$ = $APP.$sensei$common$board$symmetries$apply_point$$($history__$1$jscomp$3_last_move$jscomp$3$$, $board_size$jscomp$88_mirror_move$$, 3);
  $JSCompiler_temp$jscomp$4950_map__84044__$1_next_board$jscomp$2_p__84042$$ = $APP.$cljs$core$truth_$$($history__$1$jscomp$3_last_move$jscomp$3$$) ? $APP.$sensei$common$board$board_model$play$$.$cljs$core$IFn$_invoke$arity$2$($JSCompiler_temp$jscomp$4950_map__84044__$1_next_board$jscomp$2_p__84042$$, $board_size$jscomp$88_mirror_move$$) : null;
  $JSCompiler_temp$jscomp$4950_map__84044__$1_next_board$jscomp$2_p__84042$$ = $APP.$cljs$core$truth_$$($JSCompiler_temp$jscomp$4950_map__84044__$1_next_board$jscomp$2_p__84042$$) ? $APP.$cljs$core$_EQ_$$.$cljs$core$IFn$_invoke$arity$2$($APP.$cljs$core$update_vals$$($APP.$cljs$cst$2318$stones$$.$cljs$core$IFn$_invoke$arity$1$($JSCompiler_temp$jscomp$4950_map__84044__$1_next_board$jscomp$2_p__84042$$), $APP.$sensei$common$board$board_model$other_color$$), $APP.$cljs$cst$2318$stones$$.$cljs$core$IFn$_invoke$arity$1$($sensei$common$board$symmetries$apply_board$$($JSCompiler_temp$jscomp$4950_map__84044__$1_next_board$jscomp$2_p__84042$$))) : 
  $JSCompiler_temp$jscomp$4950_map__84044__$1_next_board$jscomp$2_p__84042$$;
  return $APP.$cljs$core$truth_$$($JSCompiler_temp$jscomp$4950_map__84044__$1_next_board$jscomp$2_p__84042$$) ? ($APP.$cljs$core$println$$.$cljs$core$IFn$_invoke$arity$variadic$($APP.$cljs$core$prim_seq$cljs$0core$0IFn$0_invoke$0arity$02$$(["Playing mirror go move", $board_size$jscomp$88_mirror_move$$])), $APP.$re_frame$router$dispatch$$(new $APP.$cljs$core$PersistentVector$$(null, 6, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$5235$sensei_DOT_frontend_DOT_play_ai_DOT_db_SLASH_play_move$$, 
  $game_uid$jscomp$151$$, $game_id$jscomp$429$$, $APP.$cljs$cst$627$white$$, $board_size$jscomp$88_mirror_move$$, !1], null))) : null;
}, $sensei$frontend$play_ai$sidebar$result_details$$ = function($game_uid$jscomp$152$$, $game_id$jscomp$430$$) {
  var $details$jscomp$5$$ = $APP.$cljs$core$deref$$($APP.$re_frame$core$subscribe$cljs$0core$0IFn$0_invoke$0arity$01$$(new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$5225$sensei_DOT_frontend_DOT_play_ai_DOT_db_SLASH_result_details$$, $game_uid$jscomp$152$$, $game_id$jscomp$430$$], null)));
  return new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$5271$table_DOT_mt_3_DOT_mb_5$$, new $APP.$cljs$core$PersistentVector$$(null, 2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$2911$thead$$, new $APP.$cljs$core$PersistentVector$$(null, 4, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$2906$tr$$, new $APP.$cljs$core$PersistentVector$$(null, 1, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, 
  [$APP.$cljs$cst$4130$th$$], null), new $APP.$cljs$core$PersistentVector$$(null, 2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$5272$th_DOT_px_3$$, new $APP.$cljs$core$PersistentVector$$(null, 2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$sensei$common$i18n$view$label$$, $APP.$cljs$cst$1616$black$$], null)], null), new $APP.$cljs$core$PersistentVector$$(null, 2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$5272$th_DOT_px_3$$, new $APP.$cljs$core$PersistentVector$$(null, 
  2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$sensei$common$i18n$view$label$$, $APP.$cljs$cst$627$white$$], null)], null)], null)], null), new $APP.$cljs$core$PersistentVector$$(null, 2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$2916$tbody$$, function() {
    return function $sensei$frontend$play_ai$sidebar$result_details_$_iter__84112$$($s__84113$$) {
      return new $APP.$cljs$core$LazySeq$$(null, function() {
        for (;;) {
          var $s__84113__$2_temp__5823__auto__$jscomp$357$$ = $APP.$cljs$core$seq$$($s__84113$$);
          if ($s__84113__$2_temp__5823__auto__$jscomp$357$$) {
            if ($APP.$cljs$core$chunked_seq_QMARK_$$($s__84113__$2_temp__5823__auto__$jscomp$357$$)) {
              var $JSCompiler_inline_result$jscomp$943_c__5501__auto__$jscomp$106$$ = $APP.$cljs$core$_chunked_first$$($s__84113__$2_temp__5823__auto__$jscomp$357$$), $size__5502__auto__$jscomp$106$$ = $APP.$cljs$core$count$$($JSCompiler_inline_result$jscomp$943_c__5501__auto__$jscomp$106$$), $b__84115_k$jscomp$426$$ = $APP.$cljs$core$chunk_buffer$$($size__5502__auto__$jscomp$106$$);
              a: {
                for (var $i__84114$jscomp$inline_4467$$ = 0;;) {
                  if ($i__84114$jscomp$inline_4467$$ < $size__5502__auto__$jscomp$106$$) {
                    var $k$jscomp$inline_4468_x$jscomp$inline_6635$$ = $APP.$cljs$core$_nth$$($JSCompiler_inline_result$jscomp$943_c__5501__auto__$jscomp$106$$, $i__84114$jscomp$inline_4467$$), $b$jscomp$inline_6634$$ = $b__84115_k$jscomp$426$$;
                    $k$jscomp$inline_4468_x$jscomp$inline_6635$$ = $APP.$cljs$core$with_meta$$(new $APP.$cljs$core$PersistentVector$$(null, 5, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$2906$tr$$, $APP.$cljs$core$_EQ_$$.$cljs$core$IFn$_invoke$arity$2$($k$jscomp$inline_4468_x$jscomp$inline_6635$$, $APP.$cljs$cst$1531$sum$$) ? new $APP.$cljs$core$PersistentArrayMap$$(null, 2, [$APP.$cljs$cst$183$class$$, $APP.$cljs$cst$5273$fw_bold$$, $APP.$cljs$cst$184$style$$, new $APP.$cljs$core$PersistentArrayMap$$(null, 
                    1, [$APP.$cljs$cst$5274$border_top$$, "1px solid black"], null)], null) : null, new $APP.$cljs$core$PersistentVector$$(null, 2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$5275$td_DOT_px_3$$, new $APP.$cljs$core$PersistentVector$$(null, 2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$sensei$common$i18n$view$label$$, $k$jscomp$inline_4468_x$jscomp$inline_6635$$], null)], null), new $APP.$cljs$core$PersistentVector$$(null, 2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, 
                    [$APP.$cljs$cst$5275$td_DOT_px_3$$, $APP.$cljs$core$get_in$cljs$0core$0IFn$0_invoke$0arity$02$$($details$jscomp$5$$, new $APP.$cljs$core$PersistentVector$$(null, 2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$k$jscomp$inline_4468_x$jscomp$inline_6635$$, $APP.$cljs$cst$1616$black$$], null))], null), new $APP.$cljs$core$PersistentVector$$(null, 2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$5275$td_DOT_px_3$$, $APP.$cljs$core$get_in$cljs$0core$0IFn$0_invoke$0arity$02$$($details$jscomp$5$$, 
                    new $APP.$cljs$core$PersistentVector$$(null, 2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$k$jscomp$inline_4468_x$jscomp$inline_6635$$, $APP.$cljs$cst$627$white$$], null))], null)], null), new $APP.$cljs$core$PersistentArrayMap$$(null, 1, [$APP.$cljs$cst$185$key$$, $k$jscomp$inline_4468_x$jscomp$inline_6635$$], null));
                    $b$jscomp$inline_6634$$.add($k$jscomp$inline_4468_x$jscomp$inline_6635$$);
                    $i__84114$jscomp$inline_4467$$ += 1;
                  } else {
                    $JSCompiler_inline_result$jscomp$943_c__5501__auto__$jscomp$106$$ = !0;
                    break a;
                  }
                }
                $JSCompiler_inline_result$jscomp$943_c__5501__auto__$jscomp$106$$ = void 0;
              }
              return $JSCompiler_inline_result$jscomp$943_c__5501__auto__$jscomp$106$$ ? $APP.$cljs$core$chunk_cons$$($APP.$cljs$core$chunk$$($b__84115_k$jscomp$426$$), $sensei$frontend$play_ai$sidebar$result_details_$_iter__84112$$($APP.$cljs$core$_chunked_rest$$($s__84113__$2_temp__5823__auto__$jscomp$357$$))) : $APP.$cljs$core$chunk_cons$$($APP.$cljs$core$chunk$$($b__84115_k$jscomp$426$$), null);
            }
            $b__84115_k$jscomp$426$$ = $APP.$cljs$core$first$$($s__84113__$2_temp__5823__auto__$jscomp$357$$);
            return $APP.$cljs$core$cons$$($APP.$cljs$core$with_meta$$(new $APP.$cljs$core$PersistentVector$$(null, 5, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$2906$tr$$, $APP.$cljs$core$_EQ_$$.$cljs$core$IFn$_invoke$arity$2$($b__84115_k$jscomp$426$$, $APP.$cljs$cst$1531$sum$$) ? new $APP.$cljs$core$PersistentArrayMap$$(null, 2, [$APP.$cljs$cst$183$class$$, $APP.$cljs$cst$5273$fw_bold$$, $APP.$cljs$cst$184$style$$, new $APP.$cljs$core$PersistentArrayMap$$(null, 1, [$APP.$cljs$cst$5274$border_top$$, 
            "1px solid black"], null)], null) : null, new $APP.$cljs$core$PersistentVector$$(null, 2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$5275$td_DOT_px_3$$, new $APP.$cljs$core$PersistentVector$$(null, 2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$sensei$common$i18n$view$label$$, $b__84115_k$jscomp$426$$], null)], null), new $APP.$cljs$core$PersistentVector$$(null, 2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$5275$td_DOT_px_3$$, 
            $APP.$cljs$core$get_in$cljs$0core$0IFn$0_invoke$0arity$02$$($details$jscomp$5$$, new $APP.$cljs$core$PersistentVector$$(null, 2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$b__84115_k$jscomp$426$$, $APP.$cljs$cst$1616$black$$], null))], null), new $APP.$cljs$core$PersistentVector$$(null, 2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$5275$td_DOT_px_3$$, $APP.$cljs$core$get_in$cljs$0core$0IFn$0_invoke$0arity$02$$($details$jscomp$5$$, new $APP.$cljs$core$PersistentVector$$(null, 
            2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$b__84115_k$jscomp$426$$, $APP.$cljs$cst$627$white$$], null))], null)], null), new $APP.$cljs$core$PersistentArrayMap$$(null, 1, [$APP.$cljs$cst$185$key$$, $b__84115_k$jscomp$426$$], null)), $sensei$frontend$play_ai$sidebar$result_details_$_iter__84112$$($APP.$cljs$core$rest$$($s__84113__$2_temp__5823__auto__$jscomp$357$$)));
          }
          return null;
        }
      }, null, null);
    }(new $APP.$cljs$core$PersistentVector$$(null, 4, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$1141$territory$$, $APP.$cljs$cst$951$total_captures$$, $APP.$cljs$cst$582$komi$$, $APP.$cljs$cst$1531$sum$$], null));
  }()], null)], null);
}, $sensei$frontend$play_ai$sidebar$display_result$$ = function($player_color$jscomp$1$$, $score$jscomp$16$$) {
  return new $APP.$cljs$core$PersistentVector$$(null, 2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$2094$div$$, new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$5280$div_DOT_alert$$, new $APP.$cljs$core$PersistentArrayMap$$(null, 1, [$APP.$cljs$cst$183$class$$, $score$jscomp$16$$ > 0 ? $APP.$cljs$cst$5276$alert_warning$$ : $score$jscomp$16$$ < 0 ? $APP.$cljs$cst$5277$alert_success$$ : $APP.$cljs$cst$5278$alert_primary$$], 
  null), new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$sensei$frontend$play_ai$sidebar$result_text$$, $player_color$jscomp$1$$, $score$jscomp$16$$], null)], null)], null);
}, $sensei$frontend$play_ai$sidebar$result_panel$$ = function($game_uid$jscomp$153$$, $game_id$jscomp$431$$, $map__84144__$1_p__84143_score$jscomp$17$$) {
  $map__84144__$1_p__84143_score$jscomp$17$$ = $APP.$cljs$core$__destructure_map$$($map__84144__$1_p__84143_score$jscomp$17$$);
  $map__84144__$1_p__84143_score$jscomp$17$$ = $APP.$cljs$core$get$cljs$0core$0IFn$0_invoke$0arity$02$$($map__84144__$1_p__84143_score$jscomp$17$$, $APP.$cljs$cst$3230$score$$);
  var $map__84146_map__84146__$1$$ = $APP.$cljs$core$deref$$($APP.$re_frame$core$subscribe$cljs$0core$0IFn$0_invoke$0arity$01$$(new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$3856$sensei_DOT_frontend_DOT_play_ai_DOT_db_SLASH_game_data$$, $game_uid$jscomp$153$$, $game_id$jscomp$431$$], null)));
  $map__84146_map__84146__$1$$ = $APP.$cljs$core$__destructure_map$$($map__84146_map__84146__$1$$);
  var $color$jscomp$107$$ = $APP.$cljs$core$get$cljs$0core$0IFn$0_invoke$0arity$02$$($map__84146_map__84146__$1$$, $APP.$cljs$cst$2311$color$$), $analysis_game_id$$ = $APP.$cljs$core$get$cljs$0core$0IFn$0_invoke$0arity$02$$($map__84146_map__84146__$1$$, $APP.$cljs$cst$5281$analysis_game_id$$);
  return new $APP.$cljs$core$PersistentVector$$(null, 4, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$2094$div$$, $APP.$cljs$core$truth_$$($analysis_game_id$$) ? new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$3316$button_DOT_btn_DOT_btn_primary$$, new $APP.$cljs$core$PersistentArrayMap$$(null, 1, [$APP.$cljs$cst$1713$on_click$$, function() {
    return $APP.$re_frame$core$dispatch$$(new $APP.$cljs$core$PersistentVector$$(null, 2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$3704$navigate$$, ["/game/", $APP.$cljs$core$str$$.$cljs$core$IFn$_invoke$arity$1$($game_uid$jscomp$153$$), "/", $APP.$cljs$core$str$$.$cljs$core$IFn$_invoke$arity$1$($analysis_game_id$$)].join("")], null));
  }], null), new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$sensei$frontend$widget$button$with_icon$$, $APP.$cljs$cst$1290$go_to_analysis$$, new $APP.$cljs$core$PersistentVector$$(null, 1, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$5282$i_DOT_fas_DOT_fa_arrow_right$$], null)], null)], null) : new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$3316$button_DOT_btn_DOT_btn_primary$$, 
  new $APP.$cljs$core$PersistentArrayMap$$(null, 1, [$APP.$cljs$cst$1713$on_click$$, function() {
    $APP.$re_frame$router$dispatch$$(new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$5253$sensei_DOT_frontend_DOT_play_ai_DOT_db_SLASH_analyze_game$$, $game_uid$jscomp$153$$, $game_id$jscomp$431$$], null));
    return $APP.$re_frame$router$dispatch$$(new $APP.$cljs$core$PersistentVector$$(null, 2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$3101$sensei_DOT_frontend_DOT_help_DOT_tutorial_SLASH_mark_seen$$, $APP.$cljs$cst$3868$play_ai_analyze_button$$], null));
  }], null), new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$sensei$frontend$widget$button$with_icon$$, $APP.$cljs$cst$1009$analyze_this_game$$, new $APP.$cljs$core$PersistentVector$$(null, 1, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$5283$i_DOT_icon_upload$$], null)], null)], null), new $APP.$cljs$core$PersistentVector$$(null, 2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$5284$div_DOT_mt_4$$, 
  new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$sensei$frontend$play_ai$sidebar$display_result$$, $color$jscomp$107$$, $map__84144__$1_p__84143_score$jscomp$17$$], null)], null), -100000 < $map__84144__$1_p__84143_score$jscomp$17$$ && $map__84144__$1_p__84143_score$jscomp$17$$ < 100000 ? new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$sensei$frontend$play_ai$sidebar$result_details$$, $game_uid$jscomp$153$$, 
  $game_id$jscomp$431$$], null) : null], null);
}, $sensei$frontend$play_ai$sidebar$score_bar$$ = function($game_uid$jscomp$154_temp__5823__auto__$jscomp$358$$, $game_id$jscomp$432$$) {
  $game_uid$jscomp$154_temp__5823__auto__$jscomp$358$$ = $APP.$cljs$core$deref$$($APP.$re_frame$core$subscribe$cljs$0core$0IFn$0_invoke$0arity$01$$(new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$5227$sensei_DOT_frontend_DOT_play_ai_DOT_db_SLASH_current_black_score$$, $game_uid$jscomp$154_temp__5823__auto__$jscomp$358$$, $game_id$jscomp$432$$], null)));
  return $APP.$cljs$core$truth_$$($game_uid$jscomp$154_temp__5823__auto__$jscomp$358$$) ? new $APP.$cljs$core$PersistentVector$$(null, 2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$5285$div_DOT_w_50_DOT_mt_2$$, new $APP.$cljs$core$PersistentVector$$(null, 2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$sensei$frontend$board$move_info$score_bar$$, $game_uid$jscomp$154_temp__5823__auto__$jscomp$358$$], null)], null) : null;
}, $sensei$frontend$play_ai$sidebar$next_turn_panel$$ = function($game_uid$jscomp$155$$, $game_id$jscomp$433$$) {
  var $map__84156_map__84156__$1$$ = $APP.$cljs$core$deref$$($APP.$re_frame$core$subscribe$cljs$0core$0IFn$0_invoke$0arity$01$$(new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$5222$sensei_DOT_frontend_DOT_play_ai_DOT_db_SLASH_board$$, $game_uid$jscomp$155$$, $game_id$jscomp$433$$], null)));
  $map__84156_map__84156__$1$$ = $APP.$cljs$core$__destructure_map$$($map__84156_map__84156__$1$$);
  var $next_turn$jscomp$16$$ = $APP.$cljs$core$get$cljs$0core$0IFn$0_invoke$0arity$02$$($map__84156_map__84156__$1$$, $APP.$cljs$cst$2320$next_turn$$);
  if ($APP.$cljs$core$_EQ_$$.$cljs$core$IFn$_invoke$arity$2$($game_uid$jscomp$155$$, $APP.$cljs$core$deref$$($APP.$re_frame$core$subscribe$cljs$0core$0IFn$0_invoke$0arity$01$$(new $APP.$cljs$core$PersistentVector$$(null, 1, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$2265$current_uid$$], null))))) {
    var $color$jscomp$108_map__84171_my_turn_QMARK_$$ = $APP.$cljs$core$deref$$($APP.$re_frame$core$subscribe$cljs$0core$0IFn$0_invoke$0arity$01$$(new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$3856$sensei_DOT_frontend_DOT_play_ai_DOT_db_SLASH_game_data$$, $game_uid$jscomp$155$$, $game_id$jscomp$433$$], null))), $loading_QMARK_$jscomp$20_map__84171__$1_map__84172$$ = $APP.$cljs$core$__destructure_map$$($color$jscomp$108_map__84171_my_turn_QMARK_$$), 
    $board_size$jscomp$89_old_humanlike_QMARK_$$ = $APP.$cljs$core$get$cljs$0core$0IFn$0_invoke$0arity$02$$($loading_QMARK_$jscomp$20_map__84171__$1_map__84172$$, $APP.$cljs$cst$746$board_size$$);
    $color$jscomp$108_map__84171_my_turn_QMARK_$$ = $APP.$cljs$core$get$cljs$0core$0IFn$0_invoke$0arity$02$$($loading_QMARK_$jscomp$20_map__84171__$1_map__84172$$, $APP.$cljs$cst$2311$color$$);
    var $bot_data$jscomp$8_can_continue_game_QMARK__map__84172__$1$$ = $APP.$cljs$core$get$cljs$0core$0IFn$0_invoke$0arity$02$$($loading_QMARK_$jscomp$20_map__84171__$1_map__84172$$, $APP.$cljs$cst$3189$bot_data$$), $already_won_by_res_QMARK_$jscomp$2_resign_button$$ = $APP.$cljs$core$get$cljs$0core$0IFn$0_invoke$0arity$02$$($loading_QMARK_$jscomp$20_map__84171__$1_map__84172$$, $APP.$cljs$cst$3191$already_won_by_res_QMARK_$$);
    $color$jscomp$108_map__84171_my_turn_QMARK_$$ = $APP.$cljs$core$_EQ_$$.$cljs$core$IFn$_invoke$arity$2$($color$jscomp$108_map__84171_my_turn_QMARK_$$, $next_turn$jscomp$16$$);
    var $turn_text$$ = new $APP.$cljs$core$PersistentVector$$(null, 2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$sensei$common$i18n$view$label$$, $color$jscomp$108_map__84171_my_turn_QMARK_$$ ? $APP.$cljs$cst$735$its_your_turn$$ : $APP.$cljs$cst$575$bot_is_thinking$$], null), $optional_spinner$$ = new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$5286$div_DOT_ms_2$$, $color$jscomp$108_map__84171_my_turn_QMARK_$$ ? new $APP.$cljs$core$PersistentArrayMap$$(null, 
    1, [$APP.$cljs$cst$183$class$$, $APP.$cljs$cst$3006$invisible$$], null) : null, new $APP.$cljs$core$PersistentVector$$(null, 1, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$5287$i_DOT_my_spinner_DOT_play_ai_spinner$$], null)], null), $pass_button$$ = $color$jscomp$108_map__84171_my_turn_QMARK_$$ ? new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$5288$button_DOT_btn_DOT_btn_primary_DOT_me_1_DOT_tutorial_anchor_play_ai_finish_game$$, 
    new $APP.$cljs$core$PersistentArrayMap$$(null, 1, [$APP.$cljs$cst$1713$on_click$$, function() {
      return $APP.$re_frame$router$dispatch$$(new $APP.$cljs$core$PersistentVector$$(null, 6, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$5235$sensei_DOT_frontend_DOT_play_ai_DOT_db_SLASH_play_move$$, $game_uid$jscomp$155$$, $game_id$jscomp$433$$, $next_turn$jscomp$16$$, $APP.$cljs$cst$1361$pass$$, !1], null));
    }], null), new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$sensei$frontend$widget$button$with_icon$$, $APP.$cljs$cst$1361$pass$$, new $APP.$cljs$core$PersistentVector$$(null, 1, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$4309$i_DOT_fas_DOT_fa_hand_paper$$], null)], null)], null) : null;
    $already_won_by_res_QMARK_$jscomp$2_resign_button$$ = $APP.$cljs$core$truth_$$($already_won_by_res_QMARK_$jscomp$2_resign_button$$) ? new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$3316$button_DOT_btn_DOT_btn_primary$$, new $APP.$cljs$core$PersistentArrayMap$$(null, 1, [$APP.$cljs$cst$1713$on_click$$, function() {
      return $APP.$re_frame$router$dispatch$$(new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$5252$sensei_DOT_frontend_DOT_play_ai_DOT_db_SLASH_accept_previous_resignation$$, $game_uid$jscomp$155$$, $game_id$jscomp$433$$], null));
    }], null), new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$sensei$frontend$widget$button$with_icon$$, $APP.$cljs$cst$1301$accept_previous_resignation$$, new $APP.$cljs$core$PersistentVector$$(null, 1, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$4788$i_DOT_fas_DOT_fa_trophy$$], null)], null)], null) : new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$3316$button_DOT_btn_DOT_btn_primary$$, 
    new $APP.$cljs$core$PersistentArrayMap$$(null, 1, [$APP.$cljs$cst$1713$on_click$$, function() {
      return $APP.$re_frame$router$dispatch$$(new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$5251$sensei_DOT_frontend_DOT_play_ai_DOT_db_SLASH_human_resigns$$, $game_uid$jscomp$155$$, $game_id$jscomp$433$$], null));
    }], null), new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$sensei$frontend$widget$button$with_icon$$, $APP.$cljs$cst$1338$resign$$, new $APP.$cljs$core$PersistentVector$$(null, 1, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$5289$i_DOT_fas_DOT_fa_flag$$], null)], null)], null);
    $board_size$jscomp$89_old_humanlike_QMARK_$$ = $APP.$cljs$core$_EQ_$$.$cljs$core$IFn$_invoke$arity$2$($APP.$cljs$cst$5169$strategy$$.$cljs$core$IFn$_invoke$arity$1$($bot_data$jscomp$8_can_continue_game_QMARK__map__84172__$1$$), $APP.$cljs$cst$5170$humanlike$$) && $APP.$cljs$core$_EQ_$$.$cljs$core$IFn$_invoke$arity$2$($board_size$jscomp$89_old_humanlike_QMARK_$$, 19) && $APP.$cljs$core$get_in$cljs$0core$0IFn$0_invoke$0arity$02$$($bot_data$jscomp$8_can_continue_game_QMARK__map__84172__$1$$, new $APP.$cljs$core$PersistentVector$$(null, 
    2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$3192$settings$$, $APP.$cljs$cst$3193$play_ai_strength$$], null)) > 10;
    $loading_QMARK_$jscomp$20_map__84171__$1_map__84172$$ = $APP.$cljs$core$deref$$($APP.$re_frame$core$subscribe$cljs$0core$0IFn$0_invoke$0arity$01$$(new $APP.$cljs$core$PersistentVector$$(null, 4, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$5179$sensei_DOT_frontend_DOT_play_ai_DOT_quota_SLASH_status_for_game$$, $game_uid$jscomp$155$$, $game_id$jscomp$433$$, $loading_QMARK_$jscomp$20_map__84171__$1_map__84172$$], null)));
    $bot_data$jscomp$8_can_continue_game_QMARK__map__84172__$1$$ = $APP.$cljs$core$__destructure_map$$($loading_QMARK_$jscomp$20_map__84171__$1_map__84172$$);
    $loading_QMARK_$jscomp$20_map__84171__$1_map__84172$$ = $APP.$cljs$core$get$cljs$0core$0IFn$0_invoke$0arity$02$$($bot_data$jscomp$8_can_continue_game_QMARK__map__84172__$1$$, $APP.$cljs$cst$3594$loading_QMARK_$$);
    $bot_data$jscomp$8_can_continue_game_QMARK__map__84172__$1$$ = $APP.$cljs$core$get$cljs$0core$0IFn$0_invoke$0arity$02$$($bot_data$jscomp$8_can_continue_game_QMARK__map__84172__$1$$, $APP.$cljs$cst$5180$can_continue_game_QMARK_$$);
    return new $APP.$cljs$core$PersistentVector$$(null, 5, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$2094$div$$, new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$3162$div_DOT_d_flex_DOT_align_items_center_DOT_justify_content_between_DOT_flex_wrap$$, new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$3297$div_DOT_d_flex_DOT_align_items_center$$, $turn_text$$, 
    $optional_spinner$$], null), new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$3297$div_DOT_d_flex_DOT_align_items_center$$, $pass_button$$, $already_won_by_res_QMARK_$jscomp$2_resign_button$$], null)], null), $APP.$cljs$core$truth_$$($APP.$cljs$core$truth_$$($map__84156_map__84156__$1$$) ? !$color$jscomp$108_map__84171_my_turn_QMARK_$$ : $map__84156_map__84156__$1$$) ? $APP.$cljs$core$truth_$$($loading_QMARK_$jscomp$20_map__84171__$1_map__84172$$) ? 
    null : $APP.$cljs$core$not$$($bot_data$jscomp$8_can_continue_game_QMARK__map__84172__$1$$) ? new $APP.$cljs$core$PersistentVector$$(null, 2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$5291$div_DOT_box_warning$$, new $APP.$cljs$core$PersistentVector$$(null, 1, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$sensei$frontend$play_ai$quota$exceeded_message$$], null)], null) : $board_size$jscomp$89_old_humanlike_QMARK_$$ ? new $APP.$cljs$core$PersistentVector$$(null, 
    4, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$sensei$frontend$play_ai$sidebar$old_humanlike_generator$$, $game_uid$jscomp$155$$, $game_id$jscomp$433$$, $map__84156_map__84156__$1$$], null) : new $APP.$cljs$core$PersistentVector$$(null, 4, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$sensei$frontend$play_ai$sidebar$ai_move_generator$$, $game_uid$jscomp$155$$, $game_id$jscomp$433$$, $map__84156_map__84156__$1$$], null) : null, $APP.$cljs$core$truth_$$($APP.$cljs$core$truth_$$($map__84156_map__84156__$1$$) ? 
    $color$jscomp$108_map__84171_my_turn_QMARK_$$ ? null : $color$jscomp$108_map__84171_my_turn_QMARK_$$ : $map__84156_map__84156__$1$$) ? new $APP.$cljs$core$PersistentVector$$(null, 4, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$sensei$frontend$play_ai$sidebar$mirror_move_generator$$, $game_uid$jscomp$155$$, $game_id$jscomp$433$$, $map__84156_map__84156__$1$$], null) : null, new $APP.$cljs$core$PersistentVector$$(null, 2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$sensei$frontend$board$trial_board$live_error_wrapper$$, 
    $game_id$jscomp$433$$], null)], null);
  }
  return new $APP.$cljs$core$PersistentVector$$(null, 2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$2094$div$$, new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$sensei$common$i18n$view$label$$, $APP.$cljs$cst$652$quiz_to_play$$, new $APP.$cljs$core$PersistentArrayMap$$(null, 1, [$APP.$cljs$cst$2311$color$$, new $APP.$cljs$core$PersistentVector$$(null, 2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$sensei$common$i18n$view$label$$, 
  $next_turn$jscomp$16$$], null)], null)], null)], null);
}, $sensei$frontend$play_ai$sidebar$advanced_settings$$ = function($ranked_QMARK_$jscomp$1$$) {
  var $or__5025__auto__$jscomp$inline_4470$$ = $APP.$cljs$core$not$$($ranked_QMARK_$jscomp$1$$);
  return $APP.$cljs$core$truth_$$($or__5025__auto__$jscomp$inline_4470$$ ? $or__5025__auto__$jscomp$inline_4470$$ : $APP.$sensei$common$env$touch_device_QMARK_$$) ? new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$2094$div$$, new $APP.$cljs$core$PersistentVector$$(null, 2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$2094$div$$, new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, 
  [$APP.$sensei$frontend$widget$expander$toggle$$, $APP.$cljs$cst$5295$advanced_play_ai_game_settings$$, new $APP.$cljs$core$PersistentVector$$(null, 2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$sensei$common$i18n$view$label$$, $APP.$cljs$cst$961$preferences$$], null)], null)], null), new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$sensei$frontend$widget$expander$body$$, $APP.$cljs$cst$5295$advanced_play_ai_game_settings$$, new $APP.$cljs$core$PersistentVector$$(null, 
  2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$sensei$frontend$play_ai$sidebar$play_ai_preferences$$, $ranked_QMARK_$jscomp$1$$], null)], null)], null) : null;
}, $sensei$frontend$play_ai$sidebar$content$$ = function($JSCompiler_temp$jscomp$inline_6638_game_uid$jscomp$156$$, $game_id$jscomp$434$$) {
  var $JSCompiler_temp_const$jscomp$4952_game_data$jscomp$41$$ = $APP.$cljs$core$deref$$($APP.$re_frame$core$subscribe$cljs$0core$0IFn$0_invoke$0arity$01$$(new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$3856$sensei_DOT_frontend_DOT_play_ai_DOT_db_SLASH_game_data$$, $JSCompiler_temp$jscomp$inline_6638_game_uid$jscomp$156$$, $game_id$jscomp$434$$], null))), $map__84255__$1_ranked_QMARK_$jscomp$2$$ = $APP.$cljs$core$__destructure_map$$($JSCompiler_temp_const$jscomp$4952_game_data$jscomp$41$$);
  $map__84255__$1_ranked_QMARK_$jscomp$2$$ = $APP.$cljs$core$get$cljs$0core$0IFn$0_invoke$0arity$02$$($map__84255__$1_ranked_QMARK_$jscomp$2$$, $APP.$cljs$cst$5210$ranked_QMARK_$$);
  var $humanlike_QMARK_$jscomp$1$$ = $APP.$cljs$core$_EQ_$$.$cljs$core$IFn$_invoke$arity$2$($APP.$cljs$core$get_in$cljs$0core$0IFn$0_invoke$0arity$02$$($JSCompiler_temp_const$jscomp$4952_game_data$jscomp$41$$, new $APP.$cljs$core$PersistentVector$$(null, 2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$3189$bot_data$$, $APP.$cljs$cst$5169$strategy$$], null)), $APP.$cljs$cst$5170$humanlike$$), $JSCompiler_temp_const$jscomp$4955$$ = $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, 
  $JSCompiler_temp_const$jscomp$4954$$ = $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, $JSCompiler_temp_const$jscomp$4953$$ = new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$sensei$frontend$play_ai$sidebar$game_row$$, $JSCompiler_temp$jscomp$inline_6638_game_uid$jscomp$156$$, $game_id$jscomp$434$$], null);
  $JSCompiler_temp_const$jscomp$4952_game_data$jscomp$41$$ = new $APP.$cljs$core$PersistentVector$$(null, 2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$sensei$frontend$play_ai$sidebar$handicap_row$$, $APP.$cljs$cst$799$handicap$$.$cljs$core$IFn$_invoke$arity$1$($JSCompiler_temp_const$jscomp$4952_game_data$jscomp$41$$)], null);
  var $JSCompiler_temp_const$jscomp$4951$$ = new $APP.$cljs$core$PersistentVector$$(null, 1, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$2162$hr$$], null), $JSCompiler_temp_const$jscomp$inline_6639_temp__5821__auto__$jscomp$inline_6637$$ = $APP.$cljs$core$deref$$($APP.$re_frame$core$subscribe$cljs$0core$0IFn$0_invoke$0arity$01$$(new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$3855$sensei_DOT_frontend_DOT_play_ai_DOT_db_SLASH_result$$, 
  $JSCompiler_temp$jscomp$inline_6638_game_uid$jscomp$156$$, $game_id$jscomp$434$$], null)));
  if ($APP.$cljs$core$truth_$$($JSCompiler_temp_const$jscomp$inline_6639_temp__5821__auto__$jscomp$inline_6637$$)) {
    $JSCompiler_temp$jscomp$inline_6638_game_uid$jscomp$156$$ = new $APP.$cljs$core$PersistentVector$$(null, 4, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$sensei$frontend$play_ai$sidebar$result_panel$$, $JSCompiler_temp$jscomp$inline_6638_game_uid$jscomp$156$$, $game_id$jscomp$434$$, $JSCompiler_temp_const$jscomp$inline_6639_temp__5821__auto__$jscomp$inline_6637$$], null);
  } else {
    $JSCompiler_temp_const$jscomp$inline_6639_temp__5821__auto__$jscomp$inline_6637$$ = $APP.$cljs$core$PersistentVector$EMPTY_NODE$$;
    var $JSCompiler_temp_const$jscomp$inline_6640$$ = new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$sensei$frontend$play_ai$sidebar$next_turn_panel$$, $JSCompiler_temp$jscomp$inline_6638_game_uid$jscomp$156$$, $game_id$jscomp$434$$], null), $and__5023__auto__$jscomp$inline_6642$$ = $APP.$cljs$core$deref$$($APP.$re_frame$core$subscribe$cljs$0core$0IFn$0_invoke$0arity$01$$(new $APP.$cljs$core$PersistentVector$$(null, 2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, 
    [$APP.$cljs$cst$1710$preference$$, $APP.$cljs$cst$5292$play_ai_show_score_QMARK_$$], null)));
    $JSCompiler_temp$jscomp$inline_6638_game_uid$jscomp$156$$ = new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $JSCompiler_temp_const$jscomp$inline_6639_temp__5821__auto__$jscomp$inline_6637$$, [$APP.$cljs$cst$1701$_LT__GT_$$, $JSCompiler_temp_const$jscomp$inline_6640$$, $APP.$cljs$core$truth_$$($APP.$cljs$core$truth_$$($and__5023__auto__$jscomp$inline_6642$$) ? $APP.$cljs$core$not$$($map__84255__$1_ranked_QMARK_$jscomp$2$$) : $and__5023__auto__$jscomp$inline_6642$$) ? new $APP.$cljs$core$PersistentVector$$(null, 
    3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$sensei$frontend$play_ai$sidebar$score_bar$$, $JSCompiler_temp$jscomp$inline_6638_game_uid$jscomp$156$$, $game_id$jscomp$434$$], null) : null], null);
  }
  return new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $JSCompiler_temp_const$jscomp$4955$$, [$APP.$sensei$frontend$board$sidebar$core$sidebar$$, null, new $APP.$cljs$core$PersistentVector$$(null, 7, 5, $JSCompiler_temp_const$jscomp$4954$$, [$APP.$cljs$cst$2094$div$$, $JSCompiler_temp_const$jscomp$4953$$, $JSCompiler_temp_const$jscomp$4952_game_data$jscomp$41$$, $JSCompiler_temp_const$jscomp$4951$$, $JSCompiler_temp$jscomp$inline_6638_game_uid$jscomp$156$$, new $APP.$cljs$core$PersistentVector$$(null, 
  1, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$2162$hr$$], null), new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$sensei$frontend$play_ai$sidebar$advanced_settings$$, $map__84255__$1_ranked_QMARK_$jscomp$2$$, $humanlike_QMARK_$jscomp$1$$], null)], null)], null);
}, $sensei$frontend$play_ai$board$board$$ = function($game_uid$jscomp$185$$, $game_id$jscomp$475$$) {
  function $on_play_move$jscomp$6$$($move$jscomp$82$$) {
    $APP.$re_frame$router$dispatch$$(new $APP.$cljs$core$PersistentVector$$(null, 6, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$5235$sensei_DOT_frontend_DOT_play_ai_DOT_db_SLASH_play_move$$, $game_uid$jscomp$185$$, $game_id$jscomp$475$$, $next_turn$jscomp$20$$, $move$jscomp$82$$, !1], null));
    return $APP.$re_frame$router$dispatch$$(new $APP.$cljs$core$PersistentVector$$(null, 2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$3101$sensei_DOT_frontend_DOT_help_DOT_tutorial_SLASH_mark_seen$$, $APP.$cljs$cst$3865$play_ai_greeting$$], null));
  }
  var $move_enabled_fn$jscomp$3_my_turn_QMARK_$jscomp$2_uid$jscomp$198$$ = $APP.$cljs$core$deref$$($APP.$re_frame$core$subscribe$cljs$0core$0IFn$0_invoke$0arity$01$$(new $APP.$cljs$core$PersistentVector$$(null, 1, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$2265$current_uid$$], null))), $board$jscomp$86_map__85956_map__85956__$1$$ = $APP.$cljs$core$deref$$($APP.$re_frame$core$subscribe$cljs$0core$0IFn$0_invoke$0arity$01$$(new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, 
  [$APP.$cljs$cst$3856$sensei_DOT_frontend_DOT_play_ai_DOT_db_SLASH_game_data$$, $game_uid$jscomp$185$$, $game_id$jscomp$475$$], null)));
  $board$jscomp$86_map__85956_map__85956__$1$$ = $APP.$cljs$core$__destructure_map$$($board$jscomp$86_map__85956_map__85956__$1$$);
  var $color$jscomp$117_ownership_data$$ = $APP.$cljs$core$get$cljs$0core$0IFn$0_invoke$0arity$02$$($board$jscomp$86_map__85956_map__85956__$1$$, $APP.$cljs$cst$2311$color$$);
  $board$jscomp$86_map__85956_map__85956__$1$$ = $APP.$cljs$core$deref$$($APP.$re_frame$core$subscribe$cljs$0core$0IFn$0_invoke$0arity$01$$(new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$5222$sensei_DOT_frontend_DOT_play_ai_DOT_db_SLASH_board$$, $game_uid$jscomp$185$$, $game_id$jscomp$475$$], null)));
  var $labels$jscomp$14_result$jscomp$159_vec__85959$$ = $APP.$cljs$core$deref$$($APP.$re_frame$core$subscribe$cljs$0core$0IFn$0_invoke$0arity$01$$(new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$3855$sensei_DOT_frontend_DOT_play_ai_DOT_db_SLASH_result$$, $game_uid$jscomp$185$$, $game_id$jscomp$475$$], null))), $result_ownership$jscomp$2$$ = $APP.$cljs$core$deref$$($APP.$re_frame$core$subscribe$cljs$0core$0IFn$0_invoke$0arity$01$$(new $APP.$cljs$core$PersistentVector$$(null, 
  3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$5223$sensei_DOT_frontend_DOT_play_ai_DOT_db_SLASH_result_ownership$$, $game_uid$jscomp$185$$, $game_id$jscomp$475$$], null))), $last_move$jscomp$7_map__85958__$1_passes$jscomp$5$$ = $APP.$cljs$core$__destructure_map$$($board$jscomp$86_map__85956_map__85956__$1$$), $next_turn$jscomp$20$$ = $APP.$cljs$core$get$cljs$0core$0IFn$0_invoke$0arity$02$$($last_move$jscomp$7_map__85958__$1_passes$jscomp$5$$, $APP.$cljs$cst$2320$next_turn$$);
  $move_enabled_fn$jscomp$3_my_turn_QMARK_$jscomp$2_uid$jscomp$198$$ = $APP.$cljs$core$_EQ_$$.$cljs$core$IFn$_invoke$arity$2$($move_enabled_fn$jscomp$3_my_turn_QMARK_$jscomp$2_uid$jscomp$198$$, $game_uid$jscomp$185$$) && $APP.$cljs$core$not$$($labels$jscomp$14_result$jscomp$159_vec__85959$$) && $APP.$cljs$core$_EQ_$$.$cljs$core$IFn$_invoke$arity$2$($color$jscomp$117_ownership_data$$, $APP.$cljs$cst$2320$next_turn$$.$cljs$core$IFn$_invoke$arity$1$($board$jscomp$86_map__85956_map__85956__$1$$));
  $move_enabled_fn$jscomp$3_my_turn_QMARK_$jscomp$2_uid$jscomp$198$$ = $APP.$cljs$core$constantly$$($move_enabled_fn$jscomp$3_my_turn_QMARK_$jscomp$2_uid$jscomp$198$$);
  $labels$jscomp$14_result$jscomp$159_vec__85959$$ = $APP.$cljs$core$peek$$($APP.$cljs$cst$2322$history$$.$cljs$core$IFn$_invoke$arity$1$($board$jscomp$86_map__85956_map__85956__$1$$));
  $last_move$jscomp$7_map__85958__$1_passes$jscomp$5$$ = $APP.$cljs$core$nth$cljs$0core$0IFn$0_invoke$0arity$03$$($labels$jscomp$14_result$jscomp$159_vec__85959$$, 0, null);
  var $humanlike_priors_last_color$jscomp$1$$ = $APP.$cljs$core$nth$cljs$0core$0IFn$0_invoke$0arity$03$$($labels$jscomp$14_result$jscomp$159_vec__85959$$, 1, null);
  $labels$jscomp$14_result$jscomp$159_vec__85959$$ = $APP.$cljs$core$truth_$$($last_move$jscomp$7_map__85958__$1_passes$jscomp$5$$) ? $APP.$cljs$core$PersistentArrayMap$createAsIfByAssoc$$([$last_move$jscomp$7_map__85958__$1_passes$jscomp$5$$, new $APP.$cljs$core$PersistentArrayMap$$(null, 2, [$APP.$cljs$cst$2311$color$$, $humanlike_priors_last_color$jscomp$1$$, $APP.$cljs$cst$2111$label$$, $APP.$cljs$cst$1873$circle$$], null)]) : null;
  $last_move$jscomp$7_map__85958__$1_passes$jscomp$5$$ = $APP.$cljs$core$_EQ_$$.$cljs$core$IFn$_invoke$arity$2$($last_move$jscomp$7_map__85958__$1_passes$jscomp$5$$, $APP.$cljs$cst$1361$pass$$) ? new $APP.$cljs$core$PersistentVector$$(null, 1, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [new $APP.$cljs$core$PersistentVector$$(null, 2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$humanlike_priors_last_color$jscomp$1$$, null], null)], null) : null;
  $humanlike_priors_last_color$jscomp$1$$ = $APP.$cljs$core$truth_$$(!1) ? $APP.$cljs$core$deref$$($APP.$re_frame$core$subscribe$cljs$0core$0IFn$0_invoke$0arity$01$$(new $APP.$cljs$core$PersistentVector$$(null, 2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$5237$sensei_DOT_frontend_DOT_play_ai_DOT_db_SLASH_probabilities$$, $game_id$jscomp$475$$], null))) : null;
  $color$jscomp$117_ownership_data$$ = $APP.$cljs$core$truth_$$($result_ownership$jscomp$2$$) ? new $APP.$cljs$core$PersistentArrayMap$$(null, 3, [$APP.$cljs$cst$139$type$$, $APP.$cljs$cst$1243$ownership$$, $APP.$cljs$cst$142$data$$, $result_ownership$jscomp$2$$, $APP.$cljs$cst$2311$color$$, $APP.$sensei$common$board$board_model$other_color$$.$cljs$core$IFn$_invoke$arity$1$ ? $APP.$sensei$common$board$board_model$other_color$$.$cljs$core$IFn$_invoke$arity$1$($color$jscomp$117_ownership_data$$) : 
  $APP.$sensei$common$board$board_model$other_color$$.call(null, $color$jscomp$117_ownership_data$$)], null) : $APP.$cljs$core$truth_$$($humanlike_priors_last_color$jscomp$1$$) ? new $APP.$cljs$core$PersistentArrayMap$$(null, 2, [$APP.$cljs$cst$139$type$$, $APP.$cljs$cst$3074$policy$$, $APP.$cljs$cst$142$data$$, $humanlike_priors_last_color$jscomp$1$$], null) : null;
  return $APP.$cljs$core$truth_$$($board$jscomp$86_map__85956_map__85956__$1$$) ? new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$2094$div$$, new $APP.$cljs$core$PersistentVector$$(null, 1, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$cljs$cst$5977$div_DOT_tutorial_anchor_play_ai_greeting_DOT_tutorial_anchor_play_ai_playing$$], null), new $APP.$cljs$core$PersistentVector$$(null, 2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, 
  [$APP.$sensei$frontend$board$board$raw_board$$, new $APP.$cljs$core$PersistentArrayMap$$(null, 7, [$APP.$cljs$cst$2326$board$$, $board$jscomp$86_map__85956_map__85956__$1$$, $APP.$cljs$cst$3420$labels$$, $labels$jscomp$14_result$jscomp$159_vec__85959$$, $APP.$cljs$cst$3490$passes$$, $last_move$jscomp$7_map__85958__$1_passes$jscomp$5$$, $APP.$cljs$cst$2358$on_play_move$$, $on_play_move$jscomp$6$$, $APP.$cljs$cst$2359$important_move_QMARK_$$, !0, $APP.$cljs$cst$2355$move_enabled_fn$$, $move_enabled_fn$jscomp$3_my_turn_QMARK_$jscomp$2_uid$jscomp$198$$, 
  $APP.$cljs$cst$1243$ownership$$, $color$jscomp$117_ownership_data$$], null)], null)], null) : null;
}, $cljs$cst$5977$div_DOT_tutorial_anchor_play_ai_greeting_DOT_tutorial_anchor_play_ai_playing$$ = new $APP.$cljs$core$Keyword$$(null, "div.tutorial-anchor-play-ai-greeting.tutorial-anchor-play-ai-playing", "div.tutorial-anchor-play-ai-greeting.tutorial-anchor-play-ai-playing", -763388527);
$APP.$JSCompiler_StaticMethods_beforeLoadModuleCode$$("play-ai");
$APP.$cljs$core$println$$.$cljs$core$IFn$_invoke$arity$variadic$($APP.$cljs$core$prim_seq$cljs$0core$0IFn$0_invoke$0arity$02$$(["LOADING GAME-PAGE"]));
$APP.$sensei$frontend$router$core$reg_page$$($APP.$cljs$cst$4812$play_ai_game$$, function($game_uid$jscomp$186_map__47704__$1_map__47705_p__47700$$) {
  $game_uid$jscomp$186_map__47704__$1_map__47705_p__47700$$ = $APP.$cljs$core$__destructure_map$$($game_uid$jscomp$186_map__47704__$1_map__47705_p__47700$$);
  $game_uid$jscomp$186_map__47704__$1_map__47705_p__47700$$ = $APP.$cljs$core$get$cljs$0core$0IFn$0_invoke$0arity$02$$($game_uid$jscomp$186_map__47704__$1_map__47705_p__47700$$, $APP.$cljs$cst$1888$params$$);
  var $game_id$jscomp$476_map__47705__$1$$ = $APP.$cljs$core$__destructure_map$$($game_uid$jscomp$186_map__47704__$1_map__47705_p__47700$$);
  $game_uid$jscomp$186_map__47704__$1_map__47705_p__47700$$ = $APP.$cljs$core$get$cljs$0core$0IFn$0_invoke$0arity$02$$($game_id$jscomp$476_map__47705__$1$$, $APP.$cljs$cst$3084$game_uid$$);
  $game_id$jscomp$476_map__47705__$1$$ = $APP.$cljs$core$get$cljs$0core$0IFn$0_invoke$0arity$02$$($game_id$jscomp$476_map__47705__$1$$, $APP.$cljs$cst$3348$game_id$$);
  var $G__47710_G__47710__$1$$ = $APP.$cljs$core$deref$$($APP.$re_frame$core$subscribe$cljs$0core$0IFn$0_invoke$0arity$01$$(new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$5220$sensei_DOT_frontend_DOT_play_ai_DOT_db_SLASH_game_data_status$$, $game_uid$jscomp$186_map__47704__$1_map__47705_p__47700$$, $game_id$jscomp$476_map__47705__$1$$], null)));
  $G__47710_G__47710__$1$$ = $G__47710_G__47710__$1$$ instanceof $APP.$cljs$core$Keyword$$ ? $G__47710_G__47710__$1$$.$fqn$ : null;
  switch($G__47710_G__47710__$1$$) {
    case "no-data":
      return $APP.$re_frame$router$dispatch$$(new $APP.$cljs$core$PersistentVector$$(null, 2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$3704$navigate$$, "/play-ai"], null)), new $APP.$cljs$core$PersistentVector$$(null, 1, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$2094$div$$], null);
    case "loading":
      return new $APP.$cljs$core$PersistentVector$$(null, 2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$5308$div_DOT_container_DOT_mt_2_GT_div_DOT_card_GT_div_DOT_card_body$$, new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$3297$div_DOT_d_flex_DOT_align_items_center$$, new $APP.$cljs$core$PersistentVector$$(null, 1, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$5309$i_DOT_my_spinner_DOT_play_ai_game_page_spinner$$], 
      null), new $APP.$cljs$core$PersistentVector$$(null, 2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$4045$span_DOT_ms_2$$, new $APP.$cljs$core$PersistentVector$$(null, 2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$sensei$common$i18n$view$label$$, $APP.$cljs$cst$1349$loading_game$$], null)], null)], null)], null);
    case "okay":
      return new $APP.$cljs$core$PersistentVector$$(null, 2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$4949$div_SHARP_game$$, new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$sensei$frontend$board$view$layout$$, new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$sensei$frontend$play_ai$board$board$$, $game_uid$jscomp$186_map__47704__$1_map__47705_p__47700$$, $game_id$jscomp$476_map__47705__$1$$], 
      null), new $APP.$cljs$core$PersistentVector$$(null, 3, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$sensei$frontend$play_ai$sidebar$content$$, $game_uid$jscomp$186_map__47704__$1_map__47705_p__47700$$, $game_id$jscomp$476_map__47705__$1$$], null)], null)], null);
    default:
      throw Error(["No matching clause: ", $APP.$cljs$core$str$$.$cljs$core$IFn$_invoke$arity$1$($G__47710_G__47710__$1$$)].join(""));
  }
}, new $APP.$cljs$core$PersistentVector$$(null, 2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, ["/play-ai/:game-uid/:game-id", new $APP.$cljs$core$PersistentArrayMap$$(null, 2, [$APP.$cljs$cst$1020$title$$, $APP.$cljs$cst$1260$play_vs_ai$$, $APP.$cljs$cst$246$start$$, function($params$jscomp$120$$) {
  return new $APP.$cljs$core$PersistentVector$$(null, 2, 5, $APP.$cljs$core$PersistentVector$EMPTY_NODE$$, [$APP.$cljs$cst$5230$sensei_DOT_frontend_DOT_play_ai_DOT_db_SLASH_set_current_game$$, $params$jscomp$120$$], null);
}], null)], null));
$APP.$module$contents$shadow$loader_mm$$.$setLoaded$();

}).call(this);